name: Close stale issues and PRs
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity.'
          close-issue-message: 'Closing this issue because it was left inactive for 7 days after being marked as stale.'
          stale-pr-message: 'This PR has been automatically marked as stale due to inactivity.'
          close-pr-message: 'Closing this PR because it was left inactive for 7 days after being marked as stale.'
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-close: -1
          operations-per-run: 100